name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  nuget-push:
    runs-on:  windows-2022
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Publish to nuget
        run: echo "Publishing to nuget simulation..."